using System.Text.Json;using NewSmartAIFactory.CompanyApi.Models;using Npgsql;using NpgsqlTypes;
namespace NewSmartAIFactory.CompanyApi.Services;
public sealed class AgentRunLogService
{
 private readonly string _cs;public AgentRunLogService(IConfiguration c)=>_cs=c.GetConnectionString("Postgres")??throw new InvalidOperationException("Connection string 'Postgres' is missing.");
 public async Task<AgentRunSummary> StartAsync(StartAgentRunRequest r,CancellationToken t){var id=Guid.NewGuid();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);await using var cmd=new NpgsqlCommand("insert into agent_runs(id,agent_id,task_id,project_id,input_text) values(@id,@agent,@task,@project,@input)",c);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("agent",r.AgentId);cmd.Parameters.AddWithValue("task",(object?)r.TaskId??DBNull.Value);cmd.Parameters.AddWithValue("project",(object?)r.ProjectId??DBNull.Value);cmd.Parameters.AddWithValue("input",r.InputText);await cmd.ExecuteNonQueryAsync(t);return(await GetAsync(id,t))!;}
 public async Task<AgentRunSummary?> CompleteAsync(Guid id,CompleteAgentRunRequest r,CancellationToken t){await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);const string sql="update agent_runs set status=@status,output_text=@output,duration_ms=@duration,files_touched=@files,decision_requested=@decision,error=@error,completed_at_utc=now() where id=@id";await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("status",r.Status);cmd.Parameters.AddWithValue("output",(object?)r.OutputText??DBNull.Value);cmd.Parameters.AddWithValue("duration",(object?)r.DurationMs??DBNull.Value);cmd.Parameters.AddWithValue("files",NpgsqlDbType.Jsonb,JsonSerializer.Serialize(r.FilesTouched??[]));cmd.Parameters.AddWithValue("decision",(object?)r.DecisionRequested??DBNull.Value);cmd.Parameters.AddWithValue("error",(object?)r.Error??DBNull.Value);if(await cmd.ExecuteNonQueryAsync(t)==0)return null;return await GetAsync(id,t);}
 public async Task<IReadOnlyList<AgentRunSummary>> ListAsync(string? agentId,string? status,int limit,CancellationToken t){const string sql="select id,agent_id,task_id,project_id,status,input_text,output_text,duration_ms,files_touched::text,decision_requested,error,started_at_utc,completed_at_utc from agent_runs where (@agent is null or agent_id=@agent) and (@status is null or status=@status) order by started_at_utc desc limit @limit";var list=new List<AgentRunSummary>();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.Add("agent",NpgsqlDbType.Text).Value=(object?)agentId??DBNull.Value;cmd.Parameters.Add("status",NpgsqlDbType.Text).Value=(object?)status??DBNull.Value;cmd.Parameters.AddWithValue("limit",Math.Clamp(limit,1,200));await using var rd=await cmd.ExecuteReaderAsync(t);while(await rd.ReadAsync(t))list.Add(Read(rd));return list;}
 public async Task<AgentRunSummary?> GetAsync(Guid id,CancellationToken t){var all=await ListByIdAsync(id,t);return all.SingleOrDefault();}
 private async Task<IReadOnlyList<AgentRunSummary>> ListByIdAsync(Guid id,CancellationToken t){const string sql="select id,agent_id,task_id,project_id,status,input_text,output_text,duration_ms,files_touched::text,decision_requested,error,started_at_utc,completed_at_utc from agent_runs where id=@id";var list=new List<AgentRunSummary>();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.AddWithValue("id",id);await using var rd=await cmd.ExecuteReaderAsync(t);while(await rd.ReadAsync(t))list.Add(Read(rd));return list;}
 private static AgentRunSummary Read(NpgsqlDataReader r){using var d=JsonDocument.Parse(r.GetString(8));return new AgentRunSummary(r.GetGuid(0),r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetString(4),r.GetString(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetInt64(7),JsonSerializer.Deserialize<string[]>(d.RootElement.GetRawText())??[],r.IsDBNull(9)?null:r.GetString(9),r.IsDBNull(10)?null:r.GetString(10),r.GetFieldValue<DateTimeOffset>(11),r.IsDBNull(12)?null:r.GetFieldValue<DateTimeOffset>(12));}
}
