using System.Net.Http.Headers;using System.Text;using System.Text.Json;using NewSmartAIFactory.CompanyApi.Models;using Npgsql;using NpgsqlTypes;
namespace NewSmartAIFactory.CompanyApi.Services;
public sealed class EventStoreService
{
 private readonly string _connectionString;private readonly string _managementUrl;public EventStoreService(IConfiguration c){_connectionString=c.GetConnectionString("Postgres")??throw new InvalidOperationException("Connection string 'Postgres' is missing.");_managementUrl=c["Infrastructure:RabbitMqManagement"]??"http://localhost:15672";}
 public async Task<DomainEventEnvelope> AppendAsync(CreateDomainEventRequest r,CancellationToken token){var id=Guid.NewGuid();var occurred=DateTimeOffset.UtcNow;var correlation=string.IsNullOrWhiteSpace(r.CorrelationId)?id.ToString("N"):r.CorrelationId;var actor=string.IsNullOrWhiteSpace(r.Actor)?"system":r.Actor;var json=r.Payload?.GetRawText()??"{}";const string sql="insert into domain_events(id,event_type,aggregate_type,aggregate_id,project_id,correlation_id,actor,payload,occurred_at_utc) values(@id,@type,@aggregateType,@aggregateId,@project,@correlation,@actor,@payload,@occurred)";await using var c=new NpgsqlConnection(_connectionString);await c.OpenAsync(token);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("type",r.EventType);cmd.Parameters.AddWithValue("aggregateType",r.AggregateType);cmd.Parameters.AddWithValue("aggregateId",r.AggregateId);cmd.Parameters.AddWithValue("project",(object?)r.ProjectId??DBNull.Value);cmd.Parameters.AddWithValue("correlation",correlation);cmd.Parameters.AddWithValue("actor",actor);cmd.Parameters.AddWithValue("payload",NpgsqlDbType.Jsonb,json);cmd.Parameters.AddWithValue("occurred",occurred);await cmd.ExecuteNonQueryAsync(token);using var doc=JsonDocument.Parse(json);return new DomainEventEnvelope(id,r.EventType,r.AggregateType,r.AggregateId,r.ProjectId,correlation,actor,doc.RootElement.Clone(),occurred);}
 public async Task<IReadOnlyList<DomainEventEnvelope>> ListAsync(string? projectId,string? eventType,int limit,CancellationToken token){const string sql="select id,event_type,aggregate_type,aggregate_id,project_id,correlation_id,actor,payload::text,occurred_at_utc,publish_attempts,published_at_utc,last_publish_error from domain_events where (@project is null or project_id=@project) and (@type is null or event_type=@type) order by occurred_at_utc desc limit @limit";var items=new List<DomainEventEnvelope>();await using var c=new NpgsqlConnection(_connectionString);await c.OpenAsync(token);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.Add("project",NpgsqlDbType.Text).Value=(object?)projectId??DBNull.Value;cmd.Parameters.Add("type",NpgsqlDbType.Text).Value=(object?)eventType??DBNull.Value;cmd.Parameters.AddWithValue("limit",Math.Clamp(limit,1,200));await using var r=await cmd.ExecuteReaderAsync(token);while(await r.ReadAsync(token)){using var doc=JsonDocument.Parse(r.GetString(7));items.Add(new DomainEventEnvelope(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetString(5),r.GetString(6),doc.RootElement.Clone(),r.GetFieldValue<DateTimeOffset>(8),r.GetInt32(9),r.IsDBNull(10)?null:r.GetFieldValue<DateTimeOffset>(10),r.IsDBNull(11)?null:r.GetString(11)));}return items;}
 public async Task<bool> PublishAsync(Guid id,CancellationToken token){var events=await ListByIdAsync(id,token);var e=events.SingleOrDefault();if(e is null)return false;try{using var client=new HttpClient();var auth=Convert.ToBase64String(Encoding.UTF8.GetBytes("guest:guest"));client.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Basic",auth);var payload=JsonSerializer.Serialize(new{e.Id,e.EventType,e.AggregateType,e.AggregateId,e.ProjectId,e.CorrelationId,e.Actor,e.Payload,e.OccurredAtUtc});var body=JsonSerializer.Serialize(new{properties=new{},routing_key="company.events",payload,payload_encoding="string"});var response=await client.PostAsync($"{_managementUrl.TrimEnd('/')}/api/exchanges/%2F/amq.default/publish",new StringContent(body,Encoding.UTF8,"application/json"),token);if(!response.IsSuccessStatusCode)throw new InvalidOperationException($"RabbitMQ returned {(int)response.StatusCode}: {await response.Content.ReadAsStringAsync(token)}");await MarkPublishAsync(id,null,token);return true;}catch(Exception ex){await MarkPublishAsync(id,ex.Message,token);return false;}}
 private async Task<IReadOnlyList<DomainEventEnvelope>> ListByIdAsync(Guid id,CancellationToken token){const string sql="select id,event_type,aggregate_type,aggregate_id,project_id,correlation_id,actor,payload::text,occurred_at_utc,publish_attempts,published_at_utc,last_publish_error from domain_events where id=@id";await using var c=new NpgsqlConnection(_connectionString);await c.OpenAsync(token);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.AddWithValue("id",id);await using var r=await cmd.ExecuteReaderAsync(token);var list=new List<DomainEventEnvelope>();while(await r.ReadAsync(token)){using var d=JsonDocument.Parse(r.GetString(7));list.Add(new DomainEventEnvelope(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetString(5),r.GetString(6),d.RootElement.Clone(),r.GetFieldValue<DateTimeOffset>(8),r.GetInt32(9),r.IsDBNull(10)?null:r.GetFieldValue<DateTimeOffset>(10),r.IsDBNull(11)?null:r.GetString(11)));}return list;}
 private async Task MarkPublishAsync(Guid id,string? error,CancellationToken token){await using var c=new NpgsqlConnection(_connectionString);await c.OpenAsync(token);await using var cmd=new NpgsqlCommand("update domain_events set publish_attempts=publish_attempts+1,published_at_utc=case when @error is null then now() else published_at_utc end,last_publish_error=@error where id=@id",c);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.Add("error",NpgsqlDbType.Text).Value=(object?)error??DBNull.Value;await cmd.ExecuteNonQueryAsync(token);}
}
