using NewSmartAIFactory.CompanyApi.Models;using Npgsql;
namespace NewSmartAIFactory.CompanyApi.Services;
public sealed class MemoryService
{
 private readonly string _cs;public MemoryService(IConfiguration c)=>_cs=c.GetConnectionString("Postgres")??throw new InvalidOperationException("Connection string 'Postgres' is missing.");
 public async Task<MemorySummary> CreateAsync(CreateMemoryRequest r,CancellationToken t){var id=Guid.NewGuid();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);await using var cmd=new NpgsqlCommand("insert into memories(id,scope,memory_type,title,content,project_id,agent_id,source) values(@id,@scope,@type,@title,@content,@project,@agent,@source)",c);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("scope",r.Scope);cmd.Parameters.AddWithValue("type",r.MemoryType);cmd.Parameters.AddWithValue("title",r.Title.Trim());cmd.Parameters.AddWithValue("content",r.Content.Trim());cmd.Parameters.AddWithValue("project",(object?)r.ProjectId??DBNull.Value);cmd.Parameters.AddWithValue("agent",(object?)r.AgentId??DBNull.Value);cmd.Parameters.AddWithValue("source",(object?)r.Source??DBNull.Value);await cmd.ExecuteNonQueryAsync(t);return(await GetAsync(id,t))!;}
 public async Task<IReadOnlyList<MemorySummary>> SearchAsync(string? q,string? scope,int limit,CancellationToken t){const string sql="select id,scope,memory_type,title,content,project_id,agent_id,source,is_obsolete,created_at_utc,updated_at_utc from memories where is_obsolete=false and (@q is null or title ilike @pattern or content ilike @pattern) and (@scope is null or scope=@scope) order by created_at_utc desc limit @limit";var list=new List<MemorySummary>();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.Add("q",NpgsqlTypes.NpgsqlDbType.Text).Value=(object?)q??DBNull.Value;cmd.Parameters.Add("pattern",NpgsqlTypes.NpgsqlDbType.Text).Value=(object?)($"%{q}%")??DBNull.Value;cmd.Parameters.Add("scope",NpgsqlTypes.NpgsqlDbType.Text).Value=(object?)scope??DBNull.Value;cmd.Parameters.AddWithValue("limit",Math.Clamp(limit,1,200));await using var rd=await cmd.ExecuteReaderAsync(t);while(await rd.ReadAsync(t))list.Add(Read(rd));return list;}
 public async Task<MemorySummary?> GetAsync(Guid id,CancellationToken t){var list=await SearchByIdAsync(id,t);return list.SingleOrDefault();}
 private async Task<IReadOnlyList<MemorySummary>> SearchByIdAsync(Guid id,CancellationToken t){const string sql="select id,scope,memory_type,title,content,project_id,agent_id,source,is_obsolete,created_at_utc,updated_at_utc from memories where id=@id";var list=new List<MemorySummary>();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(t);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.AddWithValue("id",id);await using var rd=await cmd.ExecuteReaderAsync(t);while(await rd.ReadAsync(t))list.Add(Read(rd));return list;}
 private static MemorySummary Read(NpgsqlDataReader r)=>new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.GetBoolean(8),r.GetFieldValue<DateTimeOffset>(9),r.GetFieldValue<DateTimeOffset>(10));
}
