using System.Text.Json;using NewSmartAIFactory.CompanyApi.Models;using Npgsql;
namespace NewSmartAIFactory.CompanyApi.Services;
public sealed class WorkflowRunnerService
{
 private readonly string _cs;private readonly EventStoreService _events;public WorkflowRunnerService(IConfiguration c,EventStoreService events){_cs=c.GetConnectionString("Postgres")??throw new InvalidOperationException("Connection string 'Postgres' is missing.");_events=events;}
 private static string? AgentFor(string step)=>step switch{"CEO Request"=>"ceo-assistant","PM Planning"=>"pm","BA Analysis"=>"ba","Architecture"=>"architect","Development"=>"backend","QC"=>"qc","Deployment"=>"devops","Report"=>"pm",_=>null};
 public async Task<WorkflowRunSummary> StartAsync(StartWorkflowRequest r,CancellationToken token){var id=Guid.NewGuid();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(token);await using(var cmd=new NpgsqlCommand("insert into workflow_runs(id,workflow_id,project_id,initiated_by,context) values(@id,@workflow,@project,@actor,@context)",c)){cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("workflow",r.WorkflowId);cmd.Parameters.AddWithValue("project",r.ProjectId);cmd.Parameters.AddWithValue("actor",r.InitiatedBy);cmd.Parameters.AddWithValue("context",(object?)r.Context??DBNull.Value);await cmd.ExecuteNonQueryAsync(token);}await _events.AppendAsync(new CreateDomainEventRequest("WorkflowStarted","WorkflowRun",id.ToString(),r.ProjectId,null,r.InitiatedBy,JsonSerializer.SerializeToElement(new{r.WorkflowId,r.Context})),token);return (await GetAsync(id,token))!;}
 public async Task<WorkflowRunSummary?> AdvanceAsync(Guid id,AdvanceWorkflowRequest r,CancellationToken token){await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(token);var current=await GetAsync(id,token);if(current is null||current.Status!="Running")return null;var next=current.CurrentStepOrder+1;var max=await MaxStepAsync(c,current.WorkflowId,token);var status=next>max?"Completed":"Running";await using var cmd=new NpgsqlCommand("update workflow_runs set current_step_order=@step,status=@status,updated_at_utc=now(),completed_at_utc=case when @status='Completed' then now() else completed_at_utc end where id=@id",c);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("step",Math.Min(next,max));cmd.Parameters.AddWithValue("status",status);await cmd.ExecuteNonQueryAsync(token);await _events.AppendAsync(new CreateDomainEventRequest(status=="Completed"?"WorkflowCompleted":"WorkflowAdvanced","WorkflowRun",id.ToString(),current.ProjectId,null,r.Actor,JsonSerializer.SerializeToElement(new{from=current.CurrentStepOrder,to=Math.Min(next,max),r.Note})),token);return await GetAsync(id,token);}
 public async Task<IReadOnlyList<WorkflowRunSummary>> ListAsync(string? projectId,CancellationToken token){const string sql="select r.id,r.workflow_id,r.project_id,r.status,r.current_step_order,coalesce(s.name,''),r.initiated_by,r.started_at_utc,r.updated_at_utc,r.completed_at_utc from workflow_runs r left join workflow_steps s on s.workflow_id=r.workflow_id and s.step_order=r.current_step_order where (@project is null or r.project_id=@project) order by r.updated_at_utc desc";var list=new List<WorkflowRunSummary>();await using var c=new NpgsqlConnection(_cs);await c.OpenAsync(token);await using var cmd=new NpgsqlCommand(sql,c);cmd.Parameters.Add("project",NpgsqlTypes.NpgsqlDbType.Text).Value=(object?)projectId??DBNull.Value;await using var rd=await cmd.ExecuteReaderAsync(token);while(await rd.ReadAsync(token)){var step=rd.GetString(5);list.Add(new WorkflowRunSummary(rd.GetGuid(0),rd.GetString(1),rd.GetString(2),rd.GetString(3),rd.GetInt32(4),step,AgentFor(step),rd.GetString(6),rd.GetFieldValue<DateTimeOffset>(7),rd.GetFieldValue<DateTimeOffset>(8),rd.IsDBNull(9)?null:rd.GetFieldValue<DateTimeOffset>(9)));}return list;}
 public async Task<WorkflowRunSummary?> GetAsync(Guid id,CancellationToken token){var list=await ListByIdAsync(id,token);return list.SingleOrDefault();}
 private async Task<IReadOnlyList<WorkflowRunSummary>> ListByIdAsync(Guid id,CancellationToken token){var all=await ListAsync(null,token);return all.Where(x=>x.Id==id).ToArray();}
 private static async Task<int> MaxStepAsync(NpgsqlConnection c,string workflow,CancellationToken token){await using var cmd=new NpgsqlCommand("select coalesce(max(step_order),1) from workflow_steps where workflow_id=@id",c);cmd.Parameters.AddWithValue("id",workflow);return Convert.ToInt32(await cmd.ExecuteScalarAsync(token));}
}
